output_file: prefill_result.csv

## 测试模式: all, prefill, decode
## all: 记录所有指标
## prefill: 记录 input_tokens, output_tokens, concurrency, number, ttft, p90_ttft, input_token_throughput
## decode: 记录 input_tokens, prefix_length, output_tokens, tpot, p90_tpot, concurrency, number, output_token_throughput
mode: prefill

## model config

model_config:
  model: deepseek-v3
  url: http://127.0.0.1:30000/v1/chat/completions
  api: openai
  api_key: sk-1e1b3bec65824ecc818d1cb0ff30f3e1
  tokenizer_path: deepseek-ai/DeepSeek-V3.1-Terminus


eval_config:
  ### 
  number: [10, 80, 160, 320, 640, 1280, 2560]
  concurrency: [1, 8, 16, 32, 64, 128, 256]
  rate: -1

  input_tokens: [1024]
  output_tokens: [1]
  prefix_length: [0]

